<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFmTtD9v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFmTtD9v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFmTtD9v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFmTtD9v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFmTtD9v\App_KernelDevDebugContainer([
    'container.build_hash' => 'FmTtD9v',
    'container.build_id' => '7658a8e3',
    'container.build_time' => 1729352550,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFmTtD9v');
